[package]
name = "dkg-standalone-node"
version = "3.0.0"
description = "A fresh FRAME-based Substrate node, ready for hacking."
authors = ["Webb tools"]
homepage = "https://webb.tools/"
edition = "2021"
license = "Unlicense"
publish = false
repository = "https://github.com/webb-tools/dkg-substrate"
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "dkg-standalone-node"

[dependencies]
structopt = "0.3.8"

sc-cli = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11', features = ["wasmtime"] }
sp-core = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sc-executor = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11', features = ["wasmtime"] }
sc-service = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11', features = ["wasmtime"] }
sc-telemetry = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sc-keystore = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sc-transaction-pool = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sc-transaction-pool-api = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sc-consensus-aura = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sp-consensus-aura = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sp-consensus = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sc-consensus = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sc-finality-grandpa = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sp-finality-grandpa = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sc-client-api = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sp-runtime = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sp-timestamp = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }

# These dependencies are used for the node template's RPCs
jsonrpc-core = "18.0.0"
sc-rpc = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sp-api = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sc-rpc-api = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sp-blockchain = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sp-block-builder = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
sc-basic-authorship = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
substrate-frame-rpc-system = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
pallet-transaction-payment-rpc = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }
frame-benchmarking-cli = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }

# Local dependencies
dkg-gadget = { path = "../../dkg-gadget", default-features = false }

dkg-standalone-runtime = { version = "3.0.0", path = "../runtime" }

[build-dependencies]
substrate-build-script-utils = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.11' }

[features]
default = []
runtime-benchmarks = [
	"dkg-standalone-runtime/runtime-benchmarks",
]
